language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1

cache:
  directories:
    - vendor

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit